package org.pattonvillerobotics.opmodes.autonomous;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;

import org.pattonvillerobotics.commoncode.robotclasses.drive.SimpleDrive;

@Autonomous(name = "ExampleAutonomous", group = "Examples")
public class ExampleAutonomous extends LinearOpMode
pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
        #pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, PIDControl)
        #pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, PIDControl)
public SimpleDrive simpleDrive;
public HookLiftingMechanism hooklifter;
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

        #include "JoystickDriver.c"  //Include the Joystick/Game variables driver.

        task main()
        {

    public SimpleDrive drive;

    @Override
    public void runOpMode() {

        initialize();

        waitForStart();


        wait1Msec(50);  //Waits 50 milliseconds for a new BT packet to come.

        telemetry.addData("hook position", hooklifter);

        }

    public void initialize() {
        drive = new SimpleDrive(this, hardwareMap);
        rateOfRotation = gyro.getRotation();

        motor[motorD] = 50;
        motor[motorE] = 50;
        wait1Msec(3000);cc

        motor[motorD] = 0;
        motor[motorE] = 0;
        simpleDrive = new SimpleDrive(this, hardwareMap);

        hooklifter.lower(.30);

        }
}
